name: Train Model Workflow

on:
  push:
    branches:
      - main

jobs:
  experiment:
    name: Train in Development Environment
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install distutils and other dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-distutils python3-apt

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download data from Azure Blob Storage
        run: |
          sudo apt-get install -y azure-cli
          az storage blob download-batch -d src/data/test -s UI/2024-09-06_083257_UTC/challange/ --account-name <your-storage-account-name> --account-key <your-storage-account-key>

      - name: Run training in development
        run: |
          python src/model/train.py --training_data src/data/test --reg_rate 0.01

  production:
    name: Train in Production Environment
    needs: experiment
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install distutils and other dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-distutils python3-apt

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download data from Azure Blob Storage
        run: |
          sudo apt-get install -y azure-cli
          az storage blob download-batch -d src/data/diabetes-prod-folder -s UI/2024-09-06_083257_UTC/challange/ --account-name amlchallanage9075856125 --account-key 6k9ck6tHrb+lrDXIS2kUPEItKIcFuw12G1yDFMnsfnMJnXCVtFvRCKadB8J60Lhj4M+GLd6A2TEk+ASt4OPP2Q==

      - name: Run training in production
        run: |
          python src/model/train.py --training_data src/data/diabetes-prod-folder --reg_rate 0.01
