name: Train Model Workflow

on:
  push:
    branches:
      - main

jobs:
  experiment:
    name: Train in Development Environment
    runs-on: ubuntu-latest
    environment: dev  # Use the 'dev' environment
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-distutils python3-apt azure-cli
          pip install -r requirements.txt

      - name: Download data from Azure Blob Storage
        run: |
          az storage blob download-batch -d src/data/diabetes-dev-folder -s UI/2024-09-06_083257_UTC/challange/ --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}

      - name: Run training in development
        run: |
          python src/model/train.py --training_data src/data/diabetes-dev-folder --reg_rate 0.01

  production:
    name: Train in Production Environment
    needs: experiment
    runs-on: ubuntu-latest
    environment: prod  # Use the 'prod' environment or any other environment name you have for production
    if: success()  # Ensures this job runs only if the 'experiment' job succeeds
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-distutils python3-apt azure-cli
          pip install -r requirements.txt

      - name: Download data from Azure Blob Storage
        run: |
          az storage blob download-batch -d src/data/diabetes-prod-folder -s UI/2024-09-06_083257_UTC/challange/ --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}

      - name: Run training in production
        run: |
          python src/model/train.py --training_data src/data/diabetes-prod-folder --reg_rate 0.01

      - name: Request approval
        run: echo "Manual approval required for production job."
        continue-on-error: true
